CayCanhOnline/Areas/Admin/Controllers/CuaHangController.cs
using CayCanhOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Areas.Admin.Controllers
{
    public class CuaHangController : BaseController
    {
        dbCayCanhOnlineDataContext data = new dbCayCanhOnlineDataContext();

        public ABOUT GetAbout(int id)
        {
            return (data.ABOUTs.OrderBy(n => n.id).Where(n => n.id == id).SingleOrDefault());
        }

        public ActionResult Details()
        {
            var result = data.ABOUTs.Where(dm => dm.id == 1).SingleOrDefault();
            return View(result);
        }

        public ActionResult Edit(int id)
        {
            return View(data.ABOUTs.Where(n => n.id == 1).SingleOrDefault());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f)
        {
            var about = GetAbout(1);


            if (ModelState.IsValid)
            {

                about.TieuDe = f["sTieuDe"];
                about.MoTa = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");

                about.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]);


                data.SubmitChanges();
                return RedirectToAction("Details");
            }
            return View(about);
        }
    }
}

CayCanhOnline/Areas/Admin/Controllers/DanhMucController.cs
using CayCanhOnline.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Areas.Admin.Controllers
{
    public class DanhMucController : BaseController
    {
        dbCayCanhOnlineDataContext data = new dbCayCanhOnlineDataContext();

        // GET: DanhMuc
        public ActionResult Index()
        {
            return View(from dm in data.DANHMUCs select dm);
        }

        public ActionResult Details()
        {
            int madm = int.Parse(Request.QueryString["id"]);
            var result = data.DANHMUCs.Where(dm => dm.MaDM == madm).SingleOrDefault();
            return View(result);
        }

        public DANHMUC GetDM(int id)
        {
            return (data.DANHMUCs.OrderBy(n => n.TenDM).Where(n => n.MaDM == id).SingleOrDefault());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            //NHAXUATBAN nxb = data.NHAXUATBANs.Where(n => n.MaNXB == id).SingleOrDefault();
            //return View(nxb);
            return View(GetDM(id));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                var dm = GetDM(int.Parse(Request.Form["MaDM"]));
                dm.TenDM = Request.Form["TenDM"];
                dm.AnhBia = Request.Form["AnhBia"];

                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit");
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(GetDM(id));
        }

        [HttpPost/*, ActionName("Delete")*/]
        public ActionResult Delete/*Confirm*/(int id, FormCollection f)
        {
            var dm = GetDM(id);
            if (dm == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            data.DANHMUCs.DeleteOnSubmit(dm);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(DANHMUC dm, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            if (fFileUpload == null)
            {
                ViewBag.ThongBao = "Hãy chọn ảnh bìa.";
                ViewBag.TenDM = f["TenDM"];
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    dm.TenDM = f["TenDM"];
                    dm.AnhBia = sFileName;

                    data.DANHMUCs.InsertOnSubmit(dm);
                    data.SubmitChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            //if (ModelState.IsValid)
            //{
            //    DANHMUC dm = new DANHMUC();
            //    //dm.MaNXB = int.Parse(Request.Form["MaNXB"]);
            //    dm.TenDM = Request.Form["TenDM"];
            //    dm.AnhBia = Request.Form["AnhBia"];

            //    data.SubmitChanges();
            //    //s.DonGia = Convert.ToDecimal(f["DonGia"]);
            //    //s.SLTon = Convert.ToDecimal(f["SLTon"]);
            //    data.DANHMUCs.InsertOnSubmit(dm);
            //    data.SubmitChanges();
            //    return RedirectToAction("Index");
            //}
            //else
            //{
            //    return RedirectToAction("Delete");
            //}
        }
    }
}

CayCanhOnline/Areas/Admin/Controllers/DonHangController.cs
using CayCanhOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Areas.Admin.Controllers
{
    public class DonHangController : BaseController
    {
        dbCayCanhOnlineDataContext data = new dbCayCanhOnlineDataContext();
        public ActionResult Index()
        {
            return View(from dh in data.DONDATHANGs select dh);
        }
        public ActionResult Details(int id)
        {
            var dh = data.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == id);
            if (dh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(dh);
        }
        public DONDATHANG GetDH(int id)
        {
            return data.DONDATHANGs.OrderBy(n => n.KHACHHANG.HoTen).Where(n => n.MaDonHang == id).SingleOrDefault();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(GetDH(id));
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                var dh = GetDH(int.Parse(Request.Form["MaDonHang"]));
                dh.DaThanhToan = bool.Parse(Request.Form["DaThanhToan"]);
                dh.TinhTrangGiaoHang = int.Parse(Request.Form["TinhTrangGiaoHang"]);
                dh.NgayDat = Convert.ToDateTime(Request.Form["NgayDat"]);
                dh.NgayGiao = Convert.ToDateTime(Request.Form["NgayGiao"]);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(GetDH(id));
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection f)
        {
            var dh = GetDH(id);
            if (dh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.DONDATHANGs.DeleteOnSubmit(dh);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

CayCanhOnline/Areas/Admin/Controllers/HomeController.cs
using CayCanhOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        dbCayCanhOnlineDataContext db = new dbCayCanhOnlineDataContext();
        // GET: Admin/Home
        public ActionResult Index()
        {
            if(Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        
        public ActionResult LoginCheckPartial()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection f)
        {
            var sTenDN = f["TenDN"];
            var sMatKhau = f["MatKhau"];
            //ADMIN ad = db.ADMINs.SingleOrDefault(n => n.TenDN == sTenDN && n.MatKhau == sMatKhau);
            //if (ad != null)
            //{
            //    Session["Admin"] = ad;
            //    return RedirectToAction("Index", "Home");
            //}
            //else
            //{
            //    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng!";

            //}
            //return View();


            if (String.IsNullOrEmpty(sTenDN))
            {
                ViewData["Err1"] = "Bạn chưa đăng nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["Err2"] = "Phải đăng nhập mật khẩu";
            }
            else
            {
                ADMIN kh = db.ADMINs.SingleOrDefault(n => n.TenDN == sTenDN && n.MatKhau == GetMD5(sMatKhau));
                if (kh != null)
                {
                    //ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                    Session["Admin"] = kh;
                    if (f["remember"].Contains("true"))
                    {
                        Response.Cookies["TenDN"].Value = sTenDN;
                        Response.Cookies["MatKhau"].Value = sMatKhau;
                        Response.Cookies["TenDN"].Expires = DateTime.Now.AddDays(1);
                        Response.Cookies["MatKhau"].Expires = DateTime.Now.AddDays(1);
                    }
                    else
                    {
                        Response.Cookies["TenDN"].Expires = DateTime.Now.AddDays(-1);
                        Response.Cookies["MatKhau"].Expires = DateTime.Now.AddDays(-1);
                    }
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return this.View();
        }
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;
            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");
            }
            return byte2String;
        }
        public ActionResult LoginAdminPartial()
        {
            return View();
        }
        public ActionResult DangXuat()
        {
            Session["Admin"] = null;
            return RedirectToAction("Login", "Home");
        }
    }
}

CayCanhOnline/Areas/Admin/Controllers/SuKienController.cs
using CayCanhOnline.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Areas.Admin.Controllers
{
    public class SuKienController : Controller
    {
        dbCayCanhOnlineDataContext db = new dbCayCanhOnlineDataContext();

        // GET: Admin/SanPham
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            return View(db.SUKIENs.ToList().OrderBy(n => n.NgayDang).ToPagedList(iPageNum, iPageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SUKIEN sp, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            //ViewBag.MaDM = new SelectList(db.DANHMUCs.ToList().OrderBy(n => n.TenDM), "MaDM", "TenDM");
            if (fFileUpload == null)
            {
                ViewBag.ThongBao = "Hãy chọn ảnh bìa."; 
                
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    sp.TieuDe = f["sTieuDe"];
                    sp.MoTa = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");
                    sp.AnhBia = sFileName;
                    sp.NgayDang = Convert.ToDateTime(f["dNgayDang"]);
                    sp.NgayBatDau = Convert.ToDateTime(f["dNgayBatDau"]);
                    sp.NgayKetThuc = Convert.ToDateTime(f["dNgayKetThuc"]);
                    db.SUKIENs.InsertOnSubmit(sp);
                    db.SubmitChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var sp = db.SUKIENs.SingleOrDefault(n => n.MaSK == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var sp = db.SUKIENs.SingleOrDefault(n => n.MaSK == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var sp = db.SUKIENs.SingleOrDefault(n => n.MaSK == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }


            db.SUKIENs.DeleteOnSubmit(sp);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var sp = db.SUKIENs.SingleOrDefault(n => n.MaSK == id);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(sp);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var sp = db.SUKIENs.SingleOrDefault(n => n.MaSK == int.Parse(f["iMaSK"]));


            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);

                    }
                    sp.AnhBia = sFileName;
                }
                sp.TieuDe = f["sTieuDe"];
                sp.MoTa = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");

                sp.NgayDang = Convert.ToDateTime(f["dNgayDang"]);
                sp.NgayBatDau = Convert.ToDateTime(f["dNgayBatDau"]);
                sp.NgayKetThuc = Convert.ToDateTime(f["dNgayKetThuc"]);

                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(sp);
        }
    }

}

CayCanhOnline/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container text-center" style="height:400px">
    <h2 class="mt-4">QUẢN TRỊ CÂY CẢNH GREENLIFE</h2>
</div>

CayCanhOnline/Areas/Admin/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style type="text/css">
    td {
        height: 40px;
    }
</style>
<h4 style="color:red; text-align:center;">@ViewBag.ThongBao</h4>
<h2 style="text-align:center;">ĐĂNG NHẬP</h2>
<table align="center" style="margin-left:auto;margin-right:auto; height:300px">
    @using (Html.BeginForm("Login", "Home"))
    {
        @Html.ValidationSummary(true)
        if (Request.Cookies["TenDN"] != null && Request.Cookies["MatKhau"] != null)
        {
            <tr>
                <td>Tên đăng nhập:</td>
                <td>
                    @Html.TextBox("TenDN", Request.Cookies["TenDN"].Value)
                    @ViewData["Err1"]
                </td>
            </tr>
            <tr>
                <td>Mật khẩu:</td>
                <td>
                    @Html.Password("MatKhau", Request.Cookies["MatKhau"].Value)
                    @ViewData["Err2"]
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td>Tên đăng nhập:</td>
                <td>
                    @Html.TextBox("TenDN")
                    @ViewData["Err1"]
                </td>
            </tr>
            <tr>
                <td>Mật khẩu:</td>
                <td>
                    @Html.Password("MatKhau")
                    @ViewData["Err2"]
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td>
                @Html.CheckBox("remember")<span style="font-style:italic">Nhớ thông tin đăng nhập</span>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Đăng nhập" />
            </td>
        </tr>

    }
</table>

CayCanhOnline/Areas/Admin/Views/Home/LoginAdminPartial.cshtml
@using CayCanhOnline.Models
@{
    ADMIN ad = (ADMIN)Session["Admin"];
}
@if (Session["Admin"] != null)
{
    <li><a href="#"><span class="glyphicon glyphicon-user"></span>Xin chào @ad.HoTen</a></li>
    <li><a href="@Url.Action("DangXuat", "Home")"><span class="glyphicon glyphicon-log-out"></span> Đăng xuất</a></li>

}
else
{
    <li><a href="@Url.Action("Login", "Home")"><span class="glyphicon glyphicon-log-in"></span> Đăng nhập</a></li>

}

CayCanhOnline/Areas/Admin/Views/Home/LoginCheckPartial.cshtml
@using CayCanhOnline.Models
@{
    ADMIN ad = (ADMIN)Session["Admin"];
}

<style>
    .nav-item{
        font-weight: 500;
    }
</style>

@if (Session["Admin"] != null)
{
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "SanPham")">QUẢN LÝ SẢN PHẨM</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "DanhMuc")">QUẢN LÝ DANH MỤC</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "KhachHang")">QUẢN LÝ KHÁCH HÀNG</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "DonHang")">QUẢN LÝ ĐƠN HÀNG</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Group", "ThongKe")">THỐNG KÊ</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "SuKien")">QUẢN LÝ SỰ KIỆN</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Details", "CuaHang")">QUẢN LÝ ABOUT</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link" href="#">QUẢN LÝ SẢN PHẨM</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">QUẢN LÝ DANH MỤC</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">QUẢN LÝ KHÁCH HÀNG</a>
    </li>
    <li class="nav-item">
         <a class="nav-link" href="#">QUẢN LÝ ĐƠN HÀNG</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">THỐNG KÊ</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">QUẢN LÝ SỰ KIỆN</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">QUẢN LÝ ABOUT</a>
    </li>

}