CayCanhOnline/Controllers/CayCanhOnlineController.cs
using CayCanhOnline.Models;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Controllers
{
    public class CayCanhOnlineController : Controller
    {
        dbCayCanhOnlineDataContext data = new dbCayCanhOnlineDataContext();

        private List<SANPHAM> LaySPMoi(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }

        private List<SANPHAM> LaySPTieuCanhDeBan(int count)
        {
            return data.SANPHAMs.Where(a=> a.MaDM == 1).OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }

        private List<SUKIEN> LaySuKien(int count)
        {
            return data.SUKIENs.OrderByDescending(a => a.NgayDang).Take(count).ToList();
        }

        private List<DanhMucViewModel> LayDanhMuc(int count)
        {
            return (from DANHMUCs in data.DANHMUCs
                    join SANPHAMs in data.SANPHAMs on new { MaDM = DANHMUCs.MaDM } equals new { MaDM = Convert.ToInt32(SANPHAMs.MaDM) } into SANPHAMs_join
                    from SANPHAMs in SANPHAMs_join.DefaultIfEmpty()
                    group new { DANHMUCs, SANPHAMs } by new
                    {
                        DANHMUCs.MaDM,
                        DANHMUCs.TenDM,
                        DANHMUCs.AnhBia
                    } into g
                    orderby
                      g.Count(p => p.SANPHAMs.MaDM != null) descending
                    select new DanhMucViewModel
                    
                    {
                        MaDM = (int)g.Key.MaDM,
                        TenDM = g.Key.TenDM,
                        AnhBia = g.Key.AnhBia,
                        
                    }).Take(count).ToList();
        }

        // GET: CayCanhOnline
        public ActionResult Index()
        {
            var listSPMoi = LaySPMoi(5);
            return View(listSPMoi);
        }

        public ActionResult NavPartial()
        {
            var listDM = from dm in data.DANHMUCs select dm;
            return PartialView(listDM);
        }

        public ActionResult TieuCanhDeBanPartial()
        {
            var listSP = LaySPTieuCanhDeBan(5);
            return PartialView(listSP);
        }

        public ActionResult DanhMucPartial()
        {
            var listDM = LayDanhMuc(4);
            return PartialView(listDM);
        }

        public ActionResult ChiTietSanPham(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaSP == id select s;
            return View(sp.Single());
        }

        public ActionResult DanhMucChiTietPartial()
        {
            var listDM = from dm in data.DANHMUCs select dm;
            return PartialView(listDM);
        }

        public ActionResult SPTheoDM(int iMaDM, int? page)
        {
            ViewBag.MaDM = iMaDM;
            int iSize = 4;
            int iPageNum = (page ?? 1);
            var sp = from s in data.SANPHAMs where s.MaDM == iMaDM select s;
            return View(sp.ToPagedList(iPageNum, iSize));
            
        }

        public ActionResult SuKien()
        {
            var listSK = LaySuKien(3);
            return PartialView(listSK);
        }

        public ActionResult ChiTietSuKien(int id)
        {
            var sk = from s in data.SUKIENs where s.MaSK == id select s;
            return View(sk.Single());
        }

        public ActionResult About()
        {
            var about = from s in data.ABOUTs where s.id == 1 select s;
            return View(about.Single());
        }
    }
}

CayCanhOnline/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/main.css">
    <title>@ViewBag.title</title>
</head>
<body>
    <header>
        
        @Html.Action("NavPartial", "CayCanhOnline")

    </header>

    @RenderBody()

    <!--Footer-->
    <footer class="footer-container">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="info-shop">
                            <h4>GreenLife</h4>
                            <p>Địa chỉ: 96/2 Lê Hồng Phong, Phú Lợi, Thủ Dầu Một, Bình Dương.</p>
                            <p>Điện thoại: 082 858 2484</p>
                            <p>Email: btrongtin891@gmail.com</p>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="footer-info-title">
                                    <span>Về chúng tôi</span>
                                </div>
                                <div class="footer-info-detail">
                                    <ul>
                                        <li><a href="#">Trang chủ</a></li>
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Sản phẩm</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="footer-info-title">
                                    <span>Chính sách</span>
                                </div>
                                <div class="footer-info-detail">
                                    <ul>
                                        <li><a href="#">Trang chủ</a></li>
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Sản phẩm</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="footer-info-title">
                                    <span>Hỗ trợ</span>
                                </div>
                                <div class="footer-info-detail">
                                    <ul>
                                        <li><a href="#">Trang chủ</a></li>
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Sản phẩm</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <span>Cây cảnh GreenLife | Hân hạnh được phục vụ quý khách</span>
            </div>
        </div>

    </footer>
</body>
</html>

CayCanhOnline/Views/Shared/_LayoutUserDetail.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/main.css">
    <link rel="stylesheet" href="~/Content/allproduct.css">
    <link rel="stylesheet" href="~/Content/detail.css">
    <title>@ViewBag.title</title>
</head>
<body>
    <header>
        
        @Html.Action("NavPartial","CayCanhOnline")

    </header>

    <div class="container mgt-40">
        <div class="row">
            <div class="col-md-3">
                
                @Html.Action("DanhMucChiTietPartial", "CayCanhOnline")

            </div>
            <div class="col-md-9">
                
                @RenderBody()

            </div>
        </div>
    </div>

    <!--Footer-->
    <footer class="footer-container">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="info-shop">
                            <h4>GreenLife</h4>
                            <p>Địa chỉ: 96/2 Lê Hồng Phong, Phú Lợi, Thủ Dầu Một, Bình Dương.</p>
                            <p>Điện thoại: 082 858 2484</p>
                            <p>Email: btrongtin891@gmail.com</p>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="footer-info-title">
                                    <span>Về chúng tôi</span>
                                </div>
                                <div class="footer-info-detail">
                                    <ul>
                                        <li><a href="#">Trang chủ</a></li>
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Sản phẩm</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="footer-info-title">
                                    <span>Chính sách</span>
                                </div>
                                <div class="footer-info-detail">
                                    <ul>
                                        <li><a href="#">Trang chủ</a></li>
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Sản phẩm</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="footer-info-title">
                                    <span>Hỗ trợ</span>
                                </div>
                                <div class="footer-info-detail">
                                    <ul>
                                        <li><a href="#">Trang chủ</a></li>
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Sản phẩm</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <span>Cây cảnh GreenLife | Hân hạnh được phục vụ quý khách</span>
            </div>
        </div>

    </footer>
</body>
</html>