CayCanhOnline/Areas/Admin/Controllers/KhachHangController.cs
using CayCanhOnline.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CayCanhOnline.Areas.Admin.Controllers
{
    public class KhachHangController : BaseController
    {
        dbCayCanhOnlineDataContext data = new dbCayCanhOnlineDataContext();
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            return View(data.KHACHHANGs.ToList().OrderBy(n => n.MaKH).ToPagedList(iPageNum, iPageSize));
        }
        public ActionResult Details(int id)
        {
            var kh = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }
        public KHACHHANG GetKH(int id)
        {
            return (data.KHACHHANGs.OrderBy(n => n.HoTen).Where(n => n.MaKH == id).SingleOrDefault());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(GetKH(id));
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                var kh = GetKH(int.Parse(Request.Form["MaKH"]));
                kh.HoTen = Request.Form["HoTen"];
                kh.TaiKhoan = Request.Form["TaiKhoan"];
                kh.MatKhau = Request.Form["MatKhau"];
                kh.Email = Request.Form["Email"];
                kh.DiaChi = Request.Form["DiaChi"];
                kh.DienThoai = Request.Form["DienThoai"];
                kh.NgaySinh = Convert.ToDateTime(Request.Form["NgaySinh"]);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(GetKH(id));
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection f)
        {
            var kh = GetKH(id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //var ctdh = data.CHITIETDATHANGs.Where(ct => ct.MaSach == id).ToList();
            //if (ctdh != null)
            //{
            //    ViewBag.ThongBao = "Sách này đang có trong bảng Chi tiết đặt hàng!";
            //    return RedirectToAction("Delete");
            //}
            data.KHACHHANGs.DeleteOnSubmit(kh);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection f)
        {
            if (ModelState.IsValid)
            {
                KHACHHANG kh = new KHACHHANG();
                //kh.MaKH = int.Parse(f["MaKH"]);
                kh.HoTen = Request.Form["HoTen"];
                kh.TaiKhoan = Request.Form["TaiKhoan"];
                kh.MatKhau = Request.Form["MatKhau"];
                kh.Email = Request.Form["Email"];
                kh.DiaChi = Request.Form["DiaChi"];
                kh.DienThoai = Request.Form["DienThoai"];
                kh.NgaySinh = Convert.ToDateTime(Request.Form["dNgaySinh"]);
                data.SubmitChanges();
                data.KHACHHANGs.InsertOnSubmit(kh);
                data.SubmitChanges();
                return Redirect("Index");
            }
            else
            {
                return RedirectToAction("Delete");
            }
        }
    }
}

CayCanhOnline/Areas/Admin/Views/KhachHang/Create.cshtml
@model CayCanhOnline.Models.KHACHHANG

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>THÊM KHÁCH HÀNG</h2>

@using (Html.BeginForm("Create", "KhachHang", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="control-label col-md-2">Mã khách hàng:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <p class="control-label col-md-2">Họ tên:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Tài khoản:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Mật khẩu:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Email:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Địa chỉ:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Điện thoại:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Ngày sinh:</p>

            <div class="col-md-10">
                <input type="date" name="dNgaySinh" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CayCanhOnline/Areas/Admin/Views/KhachHang/Delete.cshtml
@model CayCanhOnline.Models.KHACHHANG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style type="text/css">
    h3 {
        color: red;
        font-weight: bold;
    }
</style>
<h2>XÁC NHẬN THÔNG TIN CẦN XÓA</h2>

<h3>Bạn quyết định xóa khách hàng này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ tên:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            Tài khoản:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            Mật khẩu:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            Ngày sinh:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CayCanhOnline/Areas/Admin/Views/KhachHang/Details.cshtml
@model CayCanhOnline.Models.KHACHHANG

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">CHI TIẾT KHÁCH HÀNG</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ tên:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            Tài khoản:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            Mật khẩu:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            Ngày sinh:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CayCanhOnline/Areas/Admin/Views/KhachHang/Edit.cshtml
@model CayCanhOnline.Models.KHACHHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>ĐIỀU CHỈNH THÔNG TIN KHÁCH HÀNG</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
            <p class="control-label col-md-2">Họ tên:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Tài khoản:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Mật khẩu:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Email:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Địa chỉ:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Điện thoại:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Ngày sinh:</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CayCanhOnline/Areas/Admin/Views/KhachHang/Index.cshtml
@using CayCanhOnline.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<CayCanhOnline.Models.KHACHHANG>
@helper Truncate(String sv, int leng)
{
if (sv.Length > leng)
{
        @sv.Substring(0, leng) <text> ... </text>

}
else
{
        @sv
}
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">QUẢN LÝ THÔNG TIN KHÁCH HÀNG</h2>


<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th style="width:180px">
            Họ tên
        </th>
        <th style="width:120px">
            Tài khoản
        </th>
        <th style="width:90px">
            Mật khẩu
        </th>
        <th style="width:70px">
            Email
        </th>
        <th style=" width:140px">
            Địa chỉ
        </th>
        <th style="width:50px">
            Điện thoại
        </th>
        <th style=" width:90px">
            Ngày sinh
        </th>
        <th style="text-align:center"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TaiKhoan)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>

            <td>
                @Html.Raw(Truncate(item.Email, 20).ToString())
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>

            <td>
                @Html.FormatValue(item.NgaySinh, "{0:dd/MM/yyyy}")
            </td>
            <td style="text-align:right">
                <a href="@Url.Action("Edit",new { id = item.MaKH})" class=" btn btn-warning" role="button">Sửa</a>
                <a href="@Url.Action("Details", new{ id = item.MaKH})" class=" btn btn-primary" role="button">Chi tiết</a>
                <a href="@Url.Action("Delete", new{ id = item.MaKH})" class=" btn btn-danger" role="button">Xóa</a>
            </td>
        </tr>
    }

</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 :
Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
</style>